- name: Check if console or task is specified
  fail:
    msg: 'matomo_console_name or matomo_task_name has to be specified.'
  when: matomo_console_name == '' and matomo_task_name == ''

- name: Check if console and task are set
  fail:
    msg: 'matomo_console_name and matomo_task_name cannot used together.'
  when: matomo_console_name != '' and matomo_task_name != ''

- name: Include console tasks
  import_tasks: run_console.yml
  tags: matomo
  when: matomo_console_name != ''

- name: Include config-sync tasks
  import_tasks: run_task_config_sync.yml
  tags: matomo
  when: matomo_task_name == 'config-sync'

- name: Include import-dump tasks
  import_tasks: run_task_import_dump.yml
  tags: matomo
  when: matomo_task_name == 'import-dump'
