- name: Run matomo console task - {{ matomo_console_name }}
  shell: "php console --no-ansi -n {{ matomo_console_name }}{{ '' if matomo_url == '' else ' --url=' + matomo_url }}"
  args:
    executable: /bin/bash
    chdir: "{{ matomo_dir }}"
  become: '{{ "no" if matomo_user is undefined else "yes" }}'
  become_user: '{{ matomo_user | default(omit) }}'
  register: console_result
  when: (mysql_replication_role is undefined or mysql_replication_role == 'master') and (sync_master is undefined)

- name: Output of console - {{ matomo_console_name }}
  debug: var=console_result.stdout_lines
  when: console_result.stdout_lines is defined and console_result.stdout_lines | length
