- set_fact: working_dir="/tmp/matomo-geoip-working-dir-{{ ansible_date_time.date }}"
- set_fact: archive_file="{{ working_dir }}/{{ matomo_task_geo_source_file }}"

- name: Local prepare to provide database
  block:
    - name: Create working directory
      file:
        path: '{{ working_dir }}'
        state: directory

    - stat:
        path: '{{ archive_file }}'
        get_checksum: no
      register: archive_file_exists

    - name: Download DBIP archive file
      get_url:
        url: '{{ matomo_task_geo_url }}'
        dest: '{{ archive_file }}.gz'
      when: not archive_file_exists.stat.exists

    # there is not ansible command for gunzip at the moment
    # @see https://github.com/ansible/ansible/pull/23048
    #- name: Uncompress archive file
    #  uncompress:
    #    src: '{{ archive_file }}'
    - name: Uncompress archive file
      command: gunzip '{{ archive_file }}.gz'
      when: not archive_file_exists.stat.exists

  delegate_to: localhost

- name: Sync {{ matomo_task_geo_target_file }}
  copy:
    src: '{{ working_dir }}/{{ matomo_task_geo_source_file }}'
    dest: '{{ matomo_dir }}/misc/{{ matomo_task_geo_target_file }}'
    owner: '{{ matomo_user }}'
    group: '{{ matomo_user }}'
    force: yes
  become: "{{ matomo_task_become | default(omit) }}"
  become_user: '{{ matomo_task_become_user | default(omit) }}'
